(()=>{'use strict';
const KEY='roberto-japan-2026-v1',seed=window.JAPAN_SEED,clone=v=>JSON.parse(JSON.stringify(v)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',useGrouping:'always'}).format(Number(n)||0),dateText=(d,long=false)=>d?new Intl.DateTimeFormat('it-IT',{timeZone:'UTC',day:'numeric',month:long?'long':'short',...(long?{weekday:'long'}:{})}).format(new Date(d+'T12:00:00Z')):'Da definire';
const safeUrl=u=>{try{const url=new URL(u);return ['https:','http:'].includes(url.protocol)?url.href:''}catch{return ''}};
let model=clone(seed),view='program',selected=1,editing=false,filter='all',query='',editorState=null,undoStack=[],toastTimer,confirmationAction=null;
const main=document.querySelector('#main'),dialog=document.querySelector('#editor'),fields=document.querySelector('#editor-fields'),confirmDialog=document.querySelector('#confirmation');
function storageIssue(message){const el=document.querySelector('#storage-warning');el.textContent=message;el.hidden=false;document.querySelector('#save-state').textContent='Copia da esportare';}
function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T12:00:00Z'))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value}
function validate(raw){
 if(raw?.appId!==seed.appId||raw.schemaVersion!==1||!Array.isArray(raw.days)||!raw.days.length||raw.days.length>100||!Array.isArray(raw.reservations)||raw.reservations.length>1000||!Array.isArray(raw.budget)||raw.budget.length>50||!raw.info)throw new Error('Questa copia non è un programma Giappone 2026 valido.');
 const ids=new Set(),s=(v,max=8000)=>{if(v!=null&&typeof v!=='string')throw new Error('Una voce contiene un testo non valido.');if((v||'').length>max)throw new Error('Una voce è troppo lunga.');return v||''},unique=id=>{s(id,100);if(!id||ids.has(id))throw new Error('La copia contiene identificativi duplicati.');ids.add(id);return id},urls=arr=>{if(!Array.isArray(arr)||arr.length>30)throw new Error('Elenco collegamenti non valido.');return arr.map(u=>{s(u,6000);if(!safeUrl(u))throw new Error('I collegamenti devono iniziare con https:// o http://.');return u})};
 const days=raw.days.map(d=>{if(!validDate(d.date)||!Array.isArray(d.events)||d.events.length>300)throw new Error('Giornata non valida.');return {...d,id:unique(d.id),title:s(d.title,3000),from:s(d.from,200),to:s(d.to,200),notes:s(d.notes),events:d.events.map(e=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(e.time)&&e.time!=='')throw new Error('Orario non valido.');if(!['attivita','trasporto','pasto','nota'].includes(e.kind))throw new Error('Tipo di attività non valido.');return {id:unique(e.id),title:s(e.title,4000),time:e.time,kind:e.kind,notes:s(e.notes),links:urls(e.links||[]),bookingId:e.bookingId?s(e.bookingId,100):null,done:e.done===true}})}});
 const reservations=raw.reservations.map(b=>{if(b.date&&!validDate(b.date))throw new Error('Data prenotazione non valida.');if(!['booked','pending','consider'].includes(b.status))throw new Error('Stato prenotazione non valido.');for(const k of ['price','total','people'])if(b[k]!=null&&(!Number.isFinite(b[k])||b[k]<0||b[k]>1000000))throw new Error('Costo o partecipanti non validi.');return {id:unique(b.id),type:s(b.type,100),title:s(b.title,1000),date:b.date||'',deadline:s(b.deadline,1000),notes:s(b.notes),status:b.status,owner:s(b.owner,500),price:b.price??null,total:b.total??null,people:b.people??null,payment:s(b.payment,100),links:urls(b.links||[])}});
 const budget=raw.budget.map(b=>{if(!Number.isFinite(b.amount)||b.amount<0||b.amount>1000000)throw new Error('Budget non valido.');return {id:unique(b.id),label:s(b.label,200),amount:b.amount}});
 const info={...seed.info,...raw.info};for(const k of ['outbound','returnFlight','esim','customs','notes'])info[k]=s(info[k]);for(const k of ['esimUrl','customsUrl']){info[k]=s(info[k],6000);if(info[k]&&!safeUrl(info[k]))throw new Error('Collegamento nelle informazioni non valido.');}if(!Number.isFinite(info.exchange)||info.exchange<=0)throw new Error('Cambio valuta non valido.');
 const warnings=(Array.isArray(raw.warnings)?raw.warnings:[]).slice(0,100).map(w=>({id:s(w.id,100),dayId:s(w.dayId,100),text:s(w.text,3000)}));
 return {...clone(seed),days,reservations,budget,info,warnings,updatedAt:typeof raw.updatedAt==='string'?raw.updatedAt:null};
}
try{const saved=localStorage.getItem(KEY);if(saved)model=validate(JSON.parse(saved));}catch(e){storageIssue('Il salvataggio precedente non è leggibile. Il programma originale è disponibile; esporta una copia dopo le modifiche.');}
const id=()=>globalThis.crypto?.randomUUID?.()||`new-${Date.now()}-${Math.random().toString(36).slice(2)}`;
function toast(message){clearTimeout(toastTimer);const t=document.querySelector('#toast');t.textContent=message;t.hidden=false;toastTimer=setTimeout(()=>t.hidden=true,4200)}
function persist(){model.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(model));document.querySelector('#save-state').textContent='Salvato sul dispositivo';document.querySelector('#storage-warning').hidden=true;}catch{storageIssue('Il browser non consente il salvataggio. Le modifiche restano aperte in questa pagina: esporta una copia prima di chiuderla.');}document.querySelector('#footer-date').textContent='Ultima modifica: '+new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(model.updatedAt));}
function change(fn,message='Modifiche salvate'){undoStack.push(clone(model));if(undoStack.length>15)undoStack.shift();fn();persist();render();toast(message)}
function confirm(title,message,fn){confirmationAction=fn;document.querySelector('#confirm-title').textContent=title;document.querySelector('#confirm-message').textContent=message;confirmDialog.showModal()}
document.querySelector('#confirm-no').onclick=()=>{confirmationAction=null;confirmDialog.close()};document.querySelector('#confirm-yes').onclick=()=>{const fn=confirmationAction;confirmationAction=null;confirmDialog.close();fn?.()};
const label={attivita:'Da vedere e da fare',trasporto:'Spostamento',pasto:'A tavola',nota:'Nota pratica'};
function bookStatus(b){return b.status==='booked'?'Prenotato':b.status==='pending'?(b.type==='Altro'?'Da completare':'Da prenotare'):'Da valutare'}
function chip(b){return `<span class="chip ${b.status==='booked'?'':'pending'}">${bookStatus(b)}</span>`}
function link(u,text,cls='event-link'){const checked=safeUrl(u);return checked?`<a class="${cls}" href="${esc(checked)}" target="_blank" rel="noopener noreferrer">${esc(text)}</a>`:''}
function linksHTML(links){return links.map((u,i)=>{const t=/google.*maps|maps\.app/.test(u)?'Apri su Maps':/wikiloc/.test(u)?'Percorso Wikiloc':/tiktok/.test(u)?'Video del percorso':/klook|getyourguide|limonbus|nouhibus|hankyu|japanbus/.test(u)?'Dettagli e biglietti':`Collegamento${links.length>1?' '+(i+1):''}`;return link(u,t)}).join('')}
function mapSearch(e,day){if(['nota','trasporto'].includes(e.kind)||e.title.length>120||/^(pranzo|cena) a\s*$/i.test(e.title))return '';return link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(e.title+' Japan'),'Cerca su Maps','map-link')}
function eventHTML(e,day){const b=model.reservations.find(b=>b.id===e.bookingId);return `<article class="event ${e.done?'done':''}" data-event="${esc(e.id)}"><div class="event-time">${esc(e.time||'Libero')}</div><div class="event-card"><span class="kind-label">${label[e.kind]}</span><div class="event-title-row"><h3>${esc(e.title)}</h3><button class="check-event" data-action="done" data-id="${esc(e.id)}" aria-label="${e.done?'Segna come da fare':'Segna come completata'}: ${esc(e.title)}" aria-pressed="${e.done}">${e.done?'✓':''}</button></div>${e.notes?`<p class="event-notes">${esc(e.notes)}</p>`:''}<div class="event-bottom">${b?chip(b):''}${linksHTML(e.links)}${e.links.some(u=>/maps/.test(u))?'':mapSearch(e,day)}${/^(pranzo|cena) a\s*$/i.test(e.title)?'<span class="chip pending">Locale da scegliere</span>':''}</div>${editing?`<div class="event-actions"><button data-action="edit-event" data-id="${esc(e.id)}">Modifica o sposta</button><button data-action="delete-event" data-id="${esc(e.id)}">Elimina</button></div>`:''}</div></article>`}
function dayHTML(day,index,printing=false){const b=model.reservations.find(b=>b.id===day.hotel),warnings=model.warnings.filter(w=>w.dayId===day.id);const events=[...day.events].sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));return `<section class="day-content ${printing?'print-day':''}"><div class="day-top"><span class="eyebrow">Giorno ${index+1} · ${dateText(day.date,true)}</span>${printing?'':`<div class="day-pager"><button data-action="prev-day" aria-label="Giorno precedente" ${index===0?'disabled':''}>‹</button><button data-action="next-day" aria-label="Giorno successivo" ${index===model.days.length-1?'disabled':''}>›</button></div>`}</div><div class="day-heading"><h1>${esc(day.title)}</h1><p class="day-subtitle">${esc(day.from)}${day.to&&day.to!==day.from?' · Notte a '+esc(day.to):''}</p>${editing?`<button class="edit-day" data-action="edit-day" data-id="${esc(day.id)}">Modifica giornata</button>`:''}</div>${b?`<div class="stay-card"><div><small>Dove dormiamo</small><strong>${esc(b.title)}</strong></div>${b.links[0]?link(b.links[0],'Apri mappa','stay-map'):''}</div>`:''}${day.notes?`<div class="day-notes">${esc(day.notes)}</div>`:''}${warnings.map(w=>`<div class="notice"><div><strong>Da verificare.</strong> ${esc(w.text)}</div>${editing?`<button data-action="dismiss-warning" data-id="${esc(w.id)}">Risolto</button>`:''}</div>`).join('')}<div class="timeline-head"><h2>Il programma <span>${events.length} ${events.length===1?'voce':'voci'}</span></h2>${editing?`<button class="primary" data-action="add-event" data-id="${esc(day.id)}">＋ Aggiungi</button>`:`<span>${events.filter(e=>e.done).length}/${events.length} completate</span>`}</div><div class="timeline">${events.length?events.map(e=>eventHTML(e,day)).join(''):'<div class="empty">Giornata libera. Attiva Modifica per aggiungere un’attività.</div>'}</div></section>`}
function programHTML(){const day=model.days[selected];return `<div class="journey-art"><img src="japan-art.webp" alt="Illustrazione del Monte Fuji e di un lago in autunno"><div class="art-copy"><strong>Il nostro Giappone</strong><span>Tokyo · Kyoto · Kanazawa · Takayama · Fuji</span></div></div><div class="program-layout"><aside class="day-list" aria-label="Giornate del viaggio"><span class="rail-label">Le nostre tappe</span>${model.days.map((d,i)=>`<button class="day-button ${i===selected?'selected':''}" data-action="select-day" data-index="${i}" ${i===selected?'aria-current="date"':''}><span class="day-number">${String(i+1).padStart(2,'0')}</span><span><span class="day-city">${esc(d.from)}</span><span class="day-date">${dateText(d.date)}</span></span></button>`).join('')}</aside>${dayHTML(day,selected)}</div>`}
function bookingHTML(b){return `<article class="booking-card"><span class="booking-category">${esc(b.type||'Prenotazione')}</span><div class="booking-title-row"><h2>${esc(b.title)}</h2>${chip(b)}</div><span class="muted" style="font-size:.84rem">${dateText(b.date,true)}</span>${b.notes?`<p>${esc(b.notes)}</p>`:''}<div class="event-bottom">${linksHTML(b.links)}</div><div class="booking-meta"><div><small>Quando prenotare</small><strong>${esc(b.deadline||'Da definire')}</strong></div><div><small>Quota a persona</small><strong>${b.price==null?'Da definire':money(b.price)}</strong></div><div><small>Pagamento</small><strong>${esc(b.payment||'Da definire')}</strong></div><div><small>Chi prenota</small><strong>${esc(b.owner||'Da definire')}</strong></div>${b.people!=null?`<div><small>Partecipanti</small><strong>${b.people}</strong></div>`:''}${b.total!=null?`<div><small>Totale prenotazione</small><strong>${money(b.total)}</strong></div>`:''}</div>${editing?`<div class="event-actions"><button data-action="edit-booking" data-id="${esc(b.id)}">Modifica prenotazione</button><button data-action="delete-booking" data-id="${esc(b.id)}">Elimina</button></div>`:''}</article>`}
function bookingsHTML(){const rows=model.reservations.filter(b=>(filter==='all'||(filter==='booked'?b.status==='booked':b.status!=='booked'))&&`${b.title} ${b.notes} ${b.type}`.toLowerCase().includes(query.toLowerCase()));return `<div class="page-heading"><div class="heading-row"><h1>Prenotazioni</h1>${editing?'<button class="primary" data-action="add-booking">＋ Aggiungi</button>':''}</div><p>${model.reservations.filter(b=>b.status==='booked').length} confermate · ${model.reservations.filter(b=>b.status!=='booked').length} da organizzare</p></div><div class="booking-tools"><div class="segmented" role="group" aria-label="Filtra prenotazioni">${[['all','Tutte'],['pending','Da organizzare'],['booked','Prenotate']].map(([f,t])=>`<button data-action="filter" data-filter="${f}" class="${filter===f?'active':''}" aria-pressed="${filter===f}">${t}</button>`).join('')}</div><input class="search-field" id="booking-search" aria-label="Cerca prenotazioni" placeholder="Cerca una prenotazione…" value="${esc(query)}"></div><div class="booking-grid">${rows.length?rows.map(bookingHTML).join(''):'<div class="empty">Nessuna prenotazione corrisponde alla ricerca.</div>'}</div>`}
function budgetHTML(){const total=model.budget.reduce((s,b)=>s+b.amount,0);return `<div class="page-heading"><h1>Budget del viaggio</h1><p>La previsione a persona, dal tuo programma.</p></div><div class="cost-total"><div><small>Totale previsto a persona</small><strong>${money(total)}</strong></div><p>Include volo, alloggi, attività, pasti e trasporti. Le quote delle prenotazioni sono riportate separatamente.</p></div><div class="budget-list">${model.budget.map(b=>`<div class="budget-item"><div><strong>${esc(b.label)}</strong><small>${total?(b.amount/total*100).toFixed(1).replace('.',','):0}% del budget</small><div class="bar" aria-hidden="true"><span style="width:${total?Math.min(100,b.amount/total*100):0}%"></span></div></div><div class="budget-amount">${money(b.amount)}${editing?`<button data-action="edit-budget" data-id="${esc(b.id)}">Modifica</button>`:''}</div></div>`).join('')}</div><p class="section-note">Il budget è una previsione, non il totale delle spese pagate. Modificare una prenotazione non cambia automaticamente queste categorie: puoi aggiornare qui la previsione.</p>${model.warnings.filter(w=>w.id==='w5').map(w=>`<div class="notice"><div><strong>Importo da verificare.</strong> ${esc(w.text)}</div></div>`).join('')}`}
function infoHTML(){const i=model.info;return `<div class="page-heading"><h1>Info utili</h1><p>Le cose da tenere a portata di mano.</p></div><div class="info-grid"><section class="info-card"><h2>I nostri voli</h2><p>${esc(i.outbound)}</p><p>${esc(i.returnFlight)}</p><p>Gli orari sono quelli del foglio e si riferiscono all’ora locale indicata nella prenotazione. Verifica le differenze segnalate nel programma.</p></section><section class="info-card"><h2>Prima della partenza</h2><p>${esc(i.customs)}</p>${link(i.customsUrl,'Apri Visit Japan Web')}<p>${esc(i.esim)}</p>${link(i.esimUrl,'Vedi la eSIM')}</section><section class="info-card"><h2>Yen in euro</h2><label for="yen-amount" class="section-note">Importo in yen</label><div class="converter"><input id="yen-amount" type="number" min="0" step="1" value="1000" aria-label="Importo in yen"><span>¥ ≈</span><strong id="converted">${money(1000*i.exchange)}</strong></div><p class="section-note">Cambio di riferimento dal foglio: 1 ¥ = ${String(i.exchange).replace('.',',')} €. È una stima, non un cambio aggiornato.</p></section><section class="info-card"><h2>Note del viaggio</h2><p>${esc(i.notes||'Qui puoi aggiungere indirizzi, consigli e promemoria utili per il gruppo.')}</p>${editing?'<button class="secondary" data-action="edit-info">Modifica informazioni</button>':''}</section><section class="info-card wide"><h2>Il programma è tuo</h2><p>Premi Modifica per aggiungere un’attività, cambiare un orario o spostarla in un’altra giornata. Le modifiche vengono salvate nel browser di questo dispositivo.</p><p>Per usare le stesse modifiche su un altro telefono o PC, esporta una copia e importala sull’altro dispositivo. Il foglio Google rimane la fonte iniziale: non viene modificato dall’app.</p><div class="info-actions"><button class="primary" data-action="export">Esporta programma</button><button class="secondary" data-action="import">Importa programma</button></div>${link(model.sourceUrl,'Apri il foglio originale','source-link')}<p>Quando l’app sarà online, su iPhone aprila in Safari, premi Condividi e scegli Aggiungi alla schermata Home. Dopo la prima apertura online, programma e modifiche sono disponibili anche offline; mappe e siti esterni richiedono una connessione.</p></section></div>`}
function render(){selected=Math.max(0,Math.min(selected,model.days.length-1));main.className='view-'+view;main.innerHTML=(editing?'<div class="editing-banner">Modifica attiva · Ogni cambiamento viene salvato su questo dispositivo.</div>':'')+({program:programHTML,bookings:bookingsHTML,budget:budgetHTML,info:infoHTML}[view])();document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.querySelector('#pending-count').textContent=model.reservations.filter(b=>b.status!=='booked').length;document.querySelector('#edit-toggle').textContent=editing?'Fine modifica':'Modifica';document.querySelector('#edit-toggle').setAttribute('aria-pressed',editing);if(model.updatedAt)document.querySelector('#footer-date').textContent='Ultima modifica: '+new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short'}).format(new Date(model.updatedAt));}
function field(name,title,value,options={}){const type=options.type||'text',wide=options.wide?' wide':'';let control;if(type==='textarea')control=`<textarea id="f-${name}" name="${name}" rows="${options.rows||3}" maxlength="8000">${esc(value)}</textarea>`;else if(type==='select')control=`<select id="f-${name}" name="${name}">${options.choices.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`;else control=`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${options.required?'required':''} ${type==='number'?'min="0" max="1000000" step="'+(options.step||'.01')+'"':''} ${type==='text'?'maxlength="4000"':''}>`;return `<div class="field${wide}"><label for="f-${name}">${title}</label>${control}${options.help?`<small>${options.help}</small>`:''}</div>`}
const dayOptions=()=>model.days.map(d=>[d.id,dateText(d.date)+' · '+d.from]);
function openEditor(type,item,day){editorState={type,id:item?.id,dayId:day?.id};document.querySelector('#form-error').hidden=true;let html,title;
 if(type==='event'){const e=item||{title:'',time:'09:00',kind:'attivita',notes:'',links:[]};title=item?'Modifica o sposta attività':'Nuova attività';html=field('title','Attività',e.title,{required:true})+'<div class="field-grid">'+field('dayId','Giornata',day.id,{type:'select',choices:dayOptions()})+field('time','Orario',e.time,{type:'time'})+field('kind','Tipo',e.kind,{type:'select',choices:Object.entries(label)})+'</div><br>'+field('notes','Note',e.notes,{type:'textarea'})+field('links','Collegamenti',e.links.join('\n'),{type:'textarea',help:'Un indirizzo https:// per riga. Puoi inserire mappe, biglietti o itinerari.'});}
 if(type==='day'){title='Modifica giornata';html=field('title','Titolo',item.title,{required:true})+'<div class="field-grid">'+field('date','Data',item.date,{type:'date',required:true})+field('from','Dove ci svegliamo',item.from)+field('to','Dove dormiamo',item.to)+field('hotel','Alloggio',item.hotel||'',{type:'select',choices:[['','Nessun alloggio'],...model.reservations.filter(b=>/hotel|casa/i.test(b.type)).map(b=>[b.id,b.title])]})+'</div><br>'+field('notes','Note della giornata',item.notes,{type:'textarea'});}
 if(type==='booking'){const b=item||{title:'',type:"Attivita'",date:model.days[selected].date,status:'pending',payment:'',owner:'',deadline:'',price:null,total:null,people:null,notes:'',links:[]};title=item?'Modifica prenotazione':'Nuova prenotazione';html=field('title','Prenotazione',b.title,{required:true})+'<div class="field-grid">'+field('type','Categoria',b.type,{type:'select',choices:[['Attivita\'','Attività'],['Trasporto','Trasporto'],['Hotel/Casa','Hotel / casa'],['Altro','Altro']]})+field('date','Data attività / check-in',b.date,{type:'date'})+field('status','Prenotazione',b.status,{type:'select',choices:[['pending','Da prenotare / completare'],['booked','Prenotato'],['consider','Da valutare']]})+field('payment','Pagamento',b.payment,{type:'select',choices:[['','Da definire'],['Saldato','Saldato'],['Da Saldare','Da saldare'],['In Loco','In loco']]})+field('price','Quota a persona (€)',b.price==null?'':Number(b.price).toFixed(2),{type:'number'})+field('total','Costo totale (€)',b.total==null?'':Number(b.total).toFixed(2),{type:'number'})+field('people','Partecipanti',b.people??'',{type:'number',step:'1'})+field('owner','Chi prenota',b.owner)+'</div><br>'+field('deadline','Quando prenotare',b.deadline)+field('notes','Note',b.notes,{type:'textarea'})+field('links','Collegamenti',b.links.join('\n'),{type:'textarea',help:'Un indirizzo https:// per riga.'});}
 if(type==='budget'){title='Modifica previsione';html=field('label','Categoria',item.label,{required:true})+field('amount','Importo a persona (€)',Number(item.amount).toFixed(2),{type:'number',required:true});}
 if(type==='info'){title='Informazioni del viaggio';const i=model.info;html=field('outbound','Volo di andata',i.outbound)+field('returnFlight','Volo di ritorno',i.returnFlight)+field('customs','Prima della partenza',i.customs,{type:'textarea'})+field('customsUrl','Sito Visit Japan',i.customsUrl)+field('esim','eSIM',i.esim)+field('esimUrl','Sito eSIM',i.esimUrl)+field('exchange','Euro per 1 yen',i.exchange,{type:'number',step:'.000001'})+field('notes','Note generali',i.notes,{type:'textarea'});}
 fields.innerHTML=html;document.querySelector('#dialog-title').textContent=title;dialog.showModal();setTimeout(()=>fields.querySelector('input,textarea,select')?.focus(),0);
}
document.querySelector('#edit-form').addEventListener('submit',event=>{event.preventDefault();const v=Object.fromEntries(new FormData(event.target)),{type,id:itemId,dayId}=editorState;try{const num=k=>v[k]===''?null:Number(v[k]),arr=(v.links||'').split('\n').map(x=>x.trim()).filter(Boolean);if(arr.some(u=>!safeUrl(u)))throw new Error('Usa collegamenti completi che iniziano con https:// o http://.');if('title'in v&&!v.title.trim())throw new Error('Inserisci un titolo.');for(const key of ['date'])if(v[key]&&!validDate(v[key]))throw new Error('Inserisci una data valida.');
  const next=clone(model);
  if(type==='event'){const from=next.days.find(d=>d.id===dayId),to=next.days.find(d=>d.id===v.dayId),old=from.events.find(e=>e.id===itemId);const e={...(old||{id:id(),done:false,bookingId:null}),title:v.title.trim(),time:v.time,kind:v.kind,notes:v.notes.trim(),links:arr};if(old)from.events=from.events.filter(e=>e.id!==itemId);to.events.push(e);}
  if(type==='day'){Object.assign(next.days.find(d=>d.id===itemId),{title:v.title.trim(),date:v.date,from:v.from.trim(),to:v.to.trim(),hotel:v.hotel||null,notes:v.notes.trim()});}
  if(type==='booking'){let b=next.reservations.find(b=>b.id===itemId);if(!b){b={id:id()};next.reservations.push(b)}Object.assign(b,{title:v.title.trim(),type:v.type,date:v.date,status:v.status,payment:v.payment,owner:v.owner.trim(),deadline:v.deadline.trim(),notes:v.notes.trim(),links:arr});for(const k of ['price','total','people']){const old=b[k];b[k]=old!=null&&v[k]===Number(old).toFixed(k==='people'?0:2)?old:num(k)}}
  if(type==='budget'){const b=next.budget.find(b=>b.id===itemId);b.label=v.label.trim();if(v.amount!==Number(b.amount).toFixed(2))b.amount=Number(v.amount);}
  if(type==='info'){Object.assign(next.info,v);next.info.exchange=Number(v.exchange);}
  const checked=validate(next);dialog.close();change(()=>{model=checked});
 }catch(e){const el=document.querySelector('#form-error');el.textContent=e.message||'Controlla i campi inseriti.';el.hidden=false;el.scrollIntoView({block:'nearest'})}});
function locate(eventId){for(const day of model.days){const event=day.events.find(e=>e.id===eventId);if(event)return {day,event}}return null}
function downloadBackup(prefix='Giappone_2026_programma'){const blob=new Blob([JSON.stringify(model,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=prefix+'_'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),10000);toast('Copia del programma esportata')}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action],[data-view]');if(!el)return;document.querySelector('#tools-menu').hidden=true;document.querySelector('#menu-toggle').setAttribute('aria-expanded','false');if(el.dataset.view){view=el.dataset.view;render();return;}const action=el.dataset.action,eventId=el.dataset.id,loc=locate(eventId);if(['add-event','edit-event','delete-event','edit-day','edit-booking','add-booking','delete-booking','edit-budget','edit-info','dismiss-warning'].includes(action)&&!editing)return;
 switch(action){case'select-day':selected=Number(el.dataset.index);render();document.querySelector('.day-button.selected')?.scrollIntoView({block:'nearest',inline:'center'});break;case'prev-day':selected--;render();break;case'next-day':selected++;render();break;case'done':if(loc)change(()=>loc.event.done=!loc.event.done,loc.event.done?'Attività da fare':'Attività completata');break;case'edit-event':if(loc)openEditor('event',loc.event,loc.day);break;case'add-event':openEditor('event',null,model.days.find(d=>d.id===eventId));break;case'delete-event':if(loc)confirm('Eliminare questa attività?',loc.event.title+' · Puoi annullare l’eliminazione dal menu.',()=>change(()=>loc.day.events=loc.day.events.filter(e=>e.id!==eventId),'Attività eliminata'));break;case'edit-day':openEditor('day',model.days.find(d=>d.id===eventId));break;case'edit-booking':openEditor('booking',model.reservations.find(b=>b.id===eventId));break;case'add-booking':openEditor('booking');break;case'delete-booking':confirm('Eliminare questa prenotazione?','Il programma delle giornate rimane disponibile. Puoi annullare dal menu.',()=>change(()=>{model.reservations=model.reservations.filter(b=>b.id!==eventId);for(const d of model.days){if(d.hotel===eventId)d.hotel=null;for(const e of d.events)if(e.bookingId===eventId)e.bookingId=null}}));break;case'edit-budget':openEditor('budget',model.budget.find(b=>b.id===eventId));break;case'edit-info':openEditor('info');break;case'dismiss-warning':change(()=>model.warnings=model.warnings.filter(w=>w.id!==eventId),'Verifica completata');break;case'filter':filter=el.dataset.filter;render();break;case'close':dialog.close();break;case'export':downloadBackup();break;case'import':document.querySelector('#import-file').click();break;case'undo':if(undoStack.length){model=undoStack.pop();persist();render();toast('Ultima modifica annullata')}else toast('Nessuna modifica da annullare in questa sessione');break;case'reset':confirm('Ripristinare il programma iniziale?','Prima del ripristino scaricherò una copia del programma attuale. Puoi anche annullare dal menu.',()=>{downloadBackup('Giappone_2026_prima_del_ripristino');change(()=>model=clone(seed),'Programma iniziale ripristinato')});break;case'print':main.innerHTML=model.days.map((d,i)=>dayHTML(d,i,true)).join('');requestAnimationFrame(()=>{window.print();render()});break;
 }
});
document.querySelector('#edit-toggle').onclick=()=>{editing=!editing;render();toast(editing?'Ora puoi modificare il tuo programma':'Modifica conclusa')};
document.querySelector('#menu-toggle').onclick=()=>{const menu=document.querySelector('#tools-menu');menu.hidden=!menu.hidden;document.querySelector('#menu-toggle').setAttribute('aria-expanded',!menu.hidden)};
document.addEventListener('click',e=>{if(!e.target.closest('#tools-menu,#menu-toggle')){document.querySelector('#tools-menu').hidden=true;document.querySelector('#menu-toggle').setAttribute('aria-expanded','false')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('#tools-menu').hidden=true;document.querySelector('#menu-toggle').setAttribute('aria-expanded','false')}});
main.addEventListener('input',e=>{if(e.target.id==='booking-search'){query=e.target.value;const position=e.target.selectionStart;render();const input=document.querySelector('#booking-search');input.focus();input.setSelectionRange(position,position)}if(e.target.id==='yen-amount')document.querySelector('#converted').textContent=money(Math.max(0,Number(e.target.value)||0)*model.info.exchange)});
document.querySelector('#import-file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>5*1024*1024){toast('La copia è troppo grande. Limite: 5 MB.');return}try{const imported=validate(JSON.parse(await file.text()));confirm('Importare questo programma?',`Contiene ${imported.days.length} giornate e ${imported.reservations.length} prenotazioni. Sostituirà il programma su questo dispositivo; puoi annullare dal menu.`,()=>change(()=>{model=imported;selected=0},'Programma importato'))}catch(error){toast(error.message||'Non riesco a leggere questa copia del programma.')}};
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{model=validate(JSON.parse(e.newValue));render();toast('Programma aggiornato da un’altra scheda')}catch{}}});
render();if(location.protocol==='https:'&&'serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();


