/* Authentic Japanese sayings; Italian readings are approximate. Sources link to Japanese dictionaries. */
(()=>{'use strict';
const phrases=[{"ja":"笑う門には福来る","reading":"Uaràu cadò ni ua fucu kitàru","roman":"Warau kado ni wa fuku kitaru","it":"La fortuna arriva dove c’è allegria.","tip":"Oggi porta un sorriso: il gruppo farà il resto.","source":"https://kotobank.jp/word/笑う門には福来る-665616","emoji":"🌸"},{"ja":"七転び八起き","reading":"Nanà corobi ia òki","roman":"Nana korobi ya oki","it":"Cadi sette volte, rialzati otto.","tip":"Un imprevisto può diventare il ricordo più bello.","source":"https://kotobank.jp/word/七転び八起き-589160","emoji":"🎎"},{"ja":"一期一会","reading":"Icìgo icìe","roman":"Ichigo ichie","it":"Ogni incontro è unico: vivilo con cura.","tip":"Questa giornata non tornerà identica. Regalale un Momento.","source":"https://kotobank.jp/word/一期一会-433299","emoji":"🍵"},{"ja":"千里の道も一歩より起こる","reading":"Senri no mici mo ippo iori ocoru","roman":"Senri no michi mo ippo yori okoru","it":"Anche un lungo viaggio comincia con un passo.","tip":"Il primo passo di oggi può portarti a una bella sorpresa.","source":"https://kotobank.jp/word/千里の道も一歩より起こる-2236227","emoji":"⛩️"},{"ja":"明日は明日の風が吹く","reading":"Ascita ua ascita no case ga fucu","roman":"Ashita wa ashita no kaze ga fuku","it":"Domani soffierà il vento di domani.","tip":"Lascia un po’ di spazio alle sorprese. Oggi sei qui.","source":"https://kotowaza-dictionary.jp/k0580/","emoji":"🍃"}],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function daily(profile,date){let hash=0;for(const c of profile.id||profile.name||'')hash=(hash*31+c.charCodeAt(0))>>>0;const day=Math.floor(Date.parse(date+'T00:00:00Z')/86400000);return phrases[(hash%phrases.length+day)%phrases.length]}
function render(profile,date){
 const f=daily(profile||{id:'gruppo'},date),name=profile?.name;
 return '<section class="personal-today kitsu-today" aria-label="Kitsu e il pensiero del giorno"><div class="personal-today-heading"><div><span class="eyebrow">IL TUO VIAGGIO, INSIEME</span><h2>'+(name?'Benvenuto/a, '+esc(name)+'!':'Ciao, compagni di viaggio!')+'</h2><p>Sono Kitsu. Ho un piccolo portafortuna per te.</p></div><button type="button" class="fortune-seal kitsu-charm" data-fortune-charm aria-label="Saluta Kitsu: tocca la volpe">'+(window.JAPAN_KITSU?.markup()||'<img src="mascotte-kitsu.svg?v=20261004-notte" width="64" height="80" alt="">')+'</button></div><div class="daily-fortune kitsu-speech"><span class="fortune-label">Il pensiero di Kitsu per oggi</span><p class="fortune-japanese" lang="ja">'+f.ja+'</p><p class="fortune-meaning">'+esc(f.it)+'</p><p class="fortune-reading"><span>Si pronuncia circa</span> '+esc(f.reading)+'</p><p class="fortune-tip">'+esc(f.tip)+'</p><div class="fortune-bottom"><a class="text-button" href="'+esc(f.source)+'" target="_blank" rel="noopener noreferrer">Origine del detto ↗</a><button type="button" class="text-button" data-view="moments">Racconta il tuo oggi →</button></div></div></section>'
}
window.JAPAN_FORTUNE={render,daily};
})();