/* Momenti / private Google Drive feed. Camera and UI appended by build-drive.mjs. */
(()=>{'use strict';
const STORE='japan-moments-drive-v1',MAX_BYTES=350000,PAGE=12;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>{const paths={camera:'<path d="M4 7h4l2-3h4l2 3h4v13H4z"/><circle cx="12" cy="13" r="4"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 018 0v3"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(paths[name]||paths.camera)+'</svg>'};
let cfg=null,pendingInvite=null,incomingInvite=null,active=false,posts=[],hasMore=false,loading=false,lastFetch=0,filter='all',imageCache=new Map(),imagePending=new Map(),observer=null,stream=null,draft=null,coords=null,capturedAt=null,baseLink=location.href,status='',noticeTimer,loadGeneration=0,browsingOlder=false,revision=null,accessLost=false,cameraGeneration=0,cameraMode='user',cameraDevices=[],cameraBusy=false;
function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function save(){try{localStorage.setItem(STORE,JSON.stringify(cfg))}catch{throw Error('Questo browser non conserva l’accesso. Apri l’app in Safari o Chrome, senza modalità privata.')}}
try{const stored=read(STORE);if(stored){window.MOMENT_DRIVE_TRANSPORT.validate(stored.url);cfg=stored}const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('momenti')){const decoded=JSON.parse(atob(hash.get('momenti').replace(/-/g,'+').replace(/_/g,'/')));window.MOMENT_DRIVE_TRANSPORT.validate(decoded.url);if(decoded.provider!=='google-drive'||!/^[a-f0-9]{64}$/.test(decoded.invite))throw Error('Invito non valido');incomingInvite=decoded;if(cfg?.url!==decoded.url||!cfg?.token)pendingInvite=decoded;else{cfg.invite=decoded.invite;save()}}}catch{status='Questo invito non è valido per la versione Google Drive. Chiedi un nuovo link all’organizzatore.'}
function uid(){return cfg?.member?.id||''}
function online(){return navigator.onLine!==false}
function ready(){return !!cfg?.trip&&!!cfg?.token&&!pendingInvite&&!accessLost}
function friendly(e){const t=e.message||'Connessione non riuscita';if(/fetch|network|offline|Failed to fetch/i.test(t))return 'Connessione assente. La foto non è stata pubblicata: mantieni aperta questa schermata e riprova.';return t.slice(0,400)}
function msg(text){status=text;const el=document.querySelector('#moment-status');if(el)el.textContent=text;const toast=document.querySelector('#toast');if(toast){toast.hidden=false;toast.textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>toast.hidden=true,6000)}}
async function rpc(op,data={},auth=true){if(!online())throw Error('offline');if(!cfg?.url)throw Error('Collega prima il diario Google.');const usedUrl=cfg.url,usedToken=cfg.token;try{return await window.MOMENT_DRIVE_TRANSPORT.connect(usedUrl).call({op,data,...(auth?{token:usedToken}:{})})}catch(e){if(e.code==='ACCESS'&&auth&&cfg.url===usedUrl&&cfg.token===usedToken){pendingInvite=incomingInvite;accessLost=!pendingInvite;cfg={url:cfg.url,name:cfg.name,invite:cfg.invite};save();posts=[];for(const url of imageCache.values())URL.revokeObjectURL(url);imageCache.clear();paintMain();}throw e}}
function japanDate(value){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))}
function dayLabel(value){return new Intl.DateTimeFormat('it-IT',{timeZone:'Asia/Tokyo',weekday:'long',day:'numeric',month:'long'}).format(new Date(value))}
function timeLabel(value){return new Intl.DateTimeFormat('it-IT',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
function inviteLink(){if(!cfg?.invite)throw Error('Invito non disponibile. L’organizzatore può generarne uno nuovo.');const u=new URL(baseLink);u.hash='momenti='+btoa(JSON.stringify({provider:'google-drive',url:cfg.url,invite:cfg.invite})).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');return u.href}
function render(){const header=`<section class="moments-hero ${ready()?'compact':''}"><div class="moments-kicker">${icon('lock')} SOLO NOI, IN VIAGGIO</div><h1>Momenti<span>.</span></h1><p>Un selfie, un posto, una storia.<br>Il Giappone attraverso i nostri occhi.</p><div class="moments-hero-mark" aria-hidden="true">瞬間</div></section>`;if(accessLost)return header+`<section class="moments-welcome"><h2>Serve un nuovo invito.</h2><p>L’accesso di questo browser non è più valido. Chiedi all’organizzatore un nuovo collegamento; se sei l’organizzatore puoi recuperare l’accesso dalla guida.</p><a class="moment-guide" href="attiva-momenti.html#recupero" target="_blank" rel="noopener">Recupero dell’accesso</a><p id="moment-status" class="moment-status" role="status">${esc(status)}</p></section>`;if(pendingInvite)return header+`<section class="moments-welcome"><span class="eyebrow">SEI NEL POSTO GIUSTO</span><h2>Entra nel diario del gruppo.</h2><p>Scegli il tuo nome per condividere e vedere le foto del viaggio. Non serve registrarti.</p><button class="primary" data-moment-action="join">Entra con l’invito ${icon('arrow')}</button><p class="moment-fine">Condividi il link solo con gli amici del viaggio.</p><p id="moment-status" class="moment-status" role="status">${esc(status)}</p></section>`;if(!ready())return header+`<section class="moments-welcome"><div class="moment-round">${icon('camera')}</div><h2>I ricordi più belli<br>sono quelli insieme.</h2><p>Scatta un selfie al momento, aggiungi una frase e ritrova le foto di tutti in un unico diario privato.</p><button class="primary" data-moment-action="setup">Attiva Momenti gratuitamente ${icon('arrow')}</button><a class="moment-guide" href="attiva-momenti.html" target="_blank" rel="noopener">Apri la guida passo passo</a><p class="moment-fine">Foto nel Drive dell’organizzatore. Gli amici entrano dal link d’invito.</p><p id="moment-status" class="moment-status" role="status">${esc(status)}</p></section>`;
return header+`<div class="moment-toolbar"><div><span class="eyebrow">IL NOSTRO DIARIO PRIVATO</span><h2>${esc(cfg.trip.name)}</h2><span class="moment-identity">Sei ${esc(cfg.name)} · orari del Giappone</span></div><button class="primary moment-shoot" data-moment-action="compose">${icon('camera')} Scatta un momento</button></div><div class="moment-controls"><div class="moment-filters" aria-label="Filtra foto"><button data-moment-action="filter-all" class="${filter==='all'?'selected':''}" aria-pressed="${filter==='all'}">Tutti</button><button data-moment-action="filter-mine" class="${filter==='mine'?'selected':''}" aria-pressed="${filter==='mine'}">I miei</button></div><div><button class="text-button" data-moment-action="refresh">Aggiorna</button><button class="text-button" data-moment-action="group">Gruppo</button></div></div><p id="moment-status" class="moment-status" role="status">${esc(status)}</p><div id="moment-feed">${feedHTML()}</div><p class="moment-fine">Le foto sono visibili solo al gruppo. Aggiornamento automatico ogni 30 secondi mentre questa sezione è aperta sugli ultimi post. Serve internet.</p>`}
function card(p){const own=p.author_id===uid(),owner=cfg.trip.owner_id===uid(),image=imageCache.get(p.photo_path);return `<article class="moment-card" data-moment-id="${esc(p.id)}"><div class="moment-photo ${image?'loaded':''}" data-photo-path="${esc(p.photo_path)}">${image?`<img src="${esc(image)}" alt="Momento di ${esc(p.author_name)}" loading="lazy">`:`<button class="moment-load" data-moment-action="photo" data-post="${esc(p.id)}">${icon('camera')} Carica foto</button>`}<span class="moment-time">${timeLabel(p.created_at)} <small>JP</small></span></div><div class="moment-card-body"><div class="moment-author"><span class="moment-avatar">${esc((p.author_name||'?').charAt(0).toUpperCase())}</span><strong>${esc(p.author_name)}</strong>${own?'<span class="moment-you">Tu</span>':''}<span class="moment-location">${esc(p.place_label||'In viaggio')}</span></div>${p.caption?`<p class="moment-caption">${esc(p.caption)}</p>`:''}<div class="moment-card-foot"><span title="Ora registrata dal server">Pubblicato alle ${timeLabel(p.created_at)}${p.captured_at?` · ${p.source==='camera'?'Scatto':'Scelta foto'} ${timeLabel(p.captured_at)}`:''}</span>${p.latitude!=null&&p.longitude!=null?`<a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(p.latitude+','+p.longitude)}">Posizione ↗</a>`:''}</div><div class="moment-card-actions"><button class="text-button" data-moment-action="download" data-post="${esc(p.id)}">Salva foto</button>${own||owner?`<button class="text-button danger-text" data-moment-action="delete" data-post="${esc(p.id)}">Elimina</button>`:''}</div></div></article>`}
function feedHTML(){const visible=posts.filter(p=>filter!=='mine'||p.author_id===uid());if(!visible.length)return `<div class="moments-empty">${icon('camera')}<h3>${loading?'Carichiamo i vostri ricordi…':filter==='mine'?'Il tuo primo momento ti aspetta.':'Il viaggio comincia da qui.'}</h3><p>${loading?'Un istante e ci siamo.':online()?'Scatta il primo selfie e apri il diario del gruppo.':'Sei offline. Il programma resta consultabile; le foto richiedono internet.'}</p></div>`;let day='',html='';for(const p of visible){const d=japanDate(p.created_at);if(d!==day){if(day)html+='</div>';day=d;html+=`<h3 class="moment-day">${esc(dayLabel(p.created_at))}</h3><div class="moment-grid">`}html+=card(p)}return html+'</div>'+ (hasMore?'<button class="secondary moment-older" data-moment-action="older">'+(loading?'Caricamento…':'Mostra momenti precedenti')+'</button>':'<p class="moment-end">L’inizio dei nostri ricordi.</p>')}
function paintFeed(){const el=document.querySelector('#moment-feed');if(el){el.innerHTML=feedHTML();hydrate()}document.querySelectorAll('.moment-filters button').forEach(b=>{const on=b.dataset.momentAction==='filter-'+filter;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on)})}
function paintMain(){if(active)document.querySelector('#main').innerHTML=render();hydrate()}
async function loadFeed(older=false,force=false){if(!ready()||loading)return;loading=true;paintFeed();const generation=loadGeneration;try{const last=posts.at(-1),data=await rpc('feed',{mine:filter==='mine',limit:PAGE,...(older&&last?{before:{time:last.created_at,id:last.id}}:{}),...(!older&&!force&&revision?{revision}:{})});if(generation!==loadGeneration)return;if(!data.unchanged){hasMore=data.hasMore;posts=older?[...posts,...data.posts.filter(p=>!posts.some(a=>a.id===p.id))]:data.posts;revision=data.revision;if(data.trip)cfg.trip=data.trip;trimImages();}browsingOlder=older;lastFetch=Date.now();status=browsingOlder?'Cronologia precedente · premi Aggiorna per tornare agli ultimi momenti.':'Aggiornato alle '+timeLabel(new Date())+' · ora del Giappone';document.querySelector('#moment-status')?.replaceChildren(document.createTextNode(status));}catch(e){msg(friendly(e))}finally{loading=false;paintFeed()}}
function trimImages(){const retained=new Set(posts.map(p=>p.photo_path));for(const [path,url]of imageCache)if(!retained.has(path)){URL.revokeObjectURL(url);imageCache.delete(path)}}
async function photo(p){if(imageCache.has(p.photo_path))return imageCache.get(p.photo_path);if(imagePending.has(p.photo_path))return imagePending.get(p.photo_path);const work=(async()=>{try{const data=await rpc('photo',{id:p.id});if(data.mimeType!=='image/jpeg'||typeof data.photo!=='string'||data.photo.length>Math.ceil(MAX_BYTES/3)*4)throw Error('La foto non è disponibile.');const binary=atob(data.photo),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'}));if(!posts.some(a=>a.id===p.id)||accessLost){URL.revokeObjectURL(url);return null}imageCache.set(p.photo_path,url);const el=[...document.querySelectorAll('[data-photo-path]')].find(el=>el.dataset.photoPath===p.photo_path);if(el){el.classList.add('loaded');el.querySelector('button')?.remove();const img=document.createElement('img');img.src=url;img.alt='Momento di '+p.author_name;img.loading='lazy';el.prepend(img)}return url}catch(e){msg(friendly(e));return null}finally{imagePending.delete(p.photo_path)}})();imagePending.set(p.photo_path,work);return work}
function hydrate(){observer?.disconnect();if(!active||!ready())return;if('IntersectionObserver'in window){observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){observer.unobserve(e.target);const p=posts.find(p=>p.photo_path===e.target.dataset.photoPath);if(p&&!imageCache.has(p.photo_path))void photo(p)}},{rootMargin:'100px'});document.querySelectorAll('[data-photo-path]').forEach(el=>observer.observe(el))}}
function onView(isActive,link){active=isActive;baseLink=link||baseLink;if(active){hydrate();if(ready()&&!browsingOlder&&Date.now()-lastFetch>30000)void loadFeed()}else observer?.disconnect()}
function dialog(title,content){let el=document.querySelector('#moment-dialog');if(!el){el=document.createElement('dialog');el.id='moment-dialog';el.className='moment-dialog';document.body.append(el);el.addEventListener('close',()=>{stopCamera();if(draft?.url){URL.revokeObjectURL(draft.url);draft=null}});el.addEventListener('cancel',e=>{if(el.dataset.busy==='true'){e.preventDefault();return}stopCamera()})}el.innerHTML=`<div class="dialog-heading"><h2>${title}</h2><button type="button" class="icon-button" data-moment-action="close" aria-label="Chiudi">×</button></div>${content}<p id="moment-error" class="form-error" role="alert"></p>`;el.dataset.busy='false';if(!el.open)el.showModal();return el}
function setup(){dialog('Colleghiamo il tuo Drive.',`<p>Segui la <a href="attiva-momenti.html" target="_blank" rel="noopener">guida passo passo</a>: lo script crea la cartella privata e il registro nel tuo Google Drive. Qui servono solo il link del servizio e il codice privato ottenuti durante l’attivazione.</p><form id="moment-setup-form">${field('moment-url','URL dell’App web Google',cfg?.url||'','url','required placeholder="https://script.google.com/macros/s/…/exec" autocomplete="off"')}${field('moment-activation','Codice privato di attivazione','','password','required maxlength="64" autocomplete="off" spellcheck="false"')}${field('moment-name','Il tuo nome',cfg?.name||'','text','required maxlength="40" autocomplete="given-name"')}<button class="primary" type="submit">Collega Drive e apri il diario</button></form><p class="moment-fine">Il codice viene mostrato nel registro di esecuzione di Apps Script. Non è la tua password Google e non va condiviso con gli amici.</p>`)}
function join(){dialog('Come ti chiami?',`<form id="moment-join-form">${field('moment-name','Il nome che vedranno gli amici',cfg?.name||'','text','required maxlength="40" autocomplete="given-name"')}<p>Chi entra dal link può vedere foto, frasi e posizioni condivise nel gruppo. Pubblica solo ciò che vuoi far vedere agli amici.</p><button class="primary" type="submit">Entra nel gruppo</button></form><p class="moment-fine">Usa sempre lo stesso browser. Su un altro telefono entrerai come una nuova persona.</p>`)}

function accessAttempt(op,url,name,invite=''){
 const old=cfg?.pendingAccess;
 if(old&&old.op===op&&old.url===url&&old.name===name&&old.invite===invite&&/^[a-f0-9]{64}$/.test(old.key))return old;
 return {op,url,name,invite,key:(crypto.randomUUID()+crypto.randomUUID()).replaceAll('-','')};
}

async function submitAccess(kind){const el=document.querySelector('#moment-dialog');el.dataset.busy='true';el.querySelectorAll('button').forEach(b=>b.disabled=true);try{const name=document.querySelector('#moment-name').value.trim();if(!name)throw Error('Inserisci il tuo nome.');let result;if(kind==='setup'){const url=window.MOMENT_DRIVE_TRANSPORT.validate(document.querySelector('#moment-url').value),code=document.querySelector('#moment-activation').value.trim();if(!/^[a-f0-9]{64}$/.test(code))throw Error('Copia il codice privato di 64 caratteri dal registro di esecuzione di Apps Script.');const pendingAccess=accessAttempt('activate',url,name);cfg={url,name,pendingAccess};save();result=await rpc('activate',{code,name,accessKey:pendingAccess.key},false);if(result.invite)cfg.invite=result.invite;}else if(pendingInvite){const pendingAccess=accessAttempt('join',pendingInvite.url,name,pendingInvite.invite);cfg={url:pendingInvite.url,name,invite:pendingInvite.invite,pendingAccess};save();result=await rpc('join',{invite:cfg.invite,name,accessKey:pendingAccess.key},false);}else{const renamed=await rpc('rename',{name});cfg.name=renamed.name;cfg.member.name=renamed.name;save();el.close();paintMain();msg('Nome aggiornato. I nuovi post useranno '+name+'.');return;}cfg={...cfg,name:result.member.name,member:result.member,token:result.token,trip:result.trip};delete cfg.pendingAccess;pendingInvite=null;accessLost=false;save();if(location.hash.includes('momenti='))history.replaceState(null,'',location.pathname+location.search);el.close();posts=[];revision=null;lastFetch=0;loadGeneration++;paintMain();await loadFeed(false,true);msg('Benvenuto, '+name+'. Il diario Google è pronto.');if(kind==='setup')group();}catch(e){document.querySelector('#moment-error').textContent=friendly(e)}finally{el.dataset.busy='false';el.querySelectorAll('button').forEach(b=>b.disabled=false)}}
function group(){const owner=cfg.trip.owner_id===uid();dialog('Il nostro gruppo',`<p><strong>${esc(cfg.trip.name)}</strong><br>Sei ${esc(cfg.name)} su questo browser.</p><p>Le foto sono conservate nel Drive dell’organizzatore. Gli amici vedono il diario dall’app, senza aprire Drive.</p><div class="moment-group-buttons"><button class="primary" data-moment-action="invite">Copia invito per gli amici</button><button class="secondary" data-moment-action="rename">Cambia il mio nome</button>${owner?'<button class="secondary" data-moment-action="rotate">Genera un nuovo invito</button><button class="secondary" data-moment-action="members">Gestisci partecipanti</button>':''}</div><p id="moment-invite-output" class="moment-link" hidden></p><p class="moment-fine">Condividi l’invito solo con il gruppo. Un nuovo invito blocca i vecchi link; gli amici già entrati rimangono collegati.</p><p class="moment-fine">L’accesso personale è conservato su questo browser. Da un altro dispositivo entrerai come una nuova persona. L’organizzatore può recuperare il proprio accesso eseguendo di nuovo inizializzaMomenti nel suo Apps Script.</p><a href="attiva-momenti.html#limiti" target="_blank" rel="noopener">Spazio, privacy e conservazione dei ricordi</a>`)}
async function copyInvite(){let link;try{link=inviteLink();await navigator.clipboard.writeText(link);msg('Invito copiato. Mandalo al gruppo WhatsApp.')}catch(e){if(!link){msg(friendly(e));return}const el=document.querySelector('#moment-invite-output');if(el){el.hidden=false;el.textContent=link;const range=document.createRange();range.selectNodeContents(el);getSelection().removeAllRanges();getSelection().addRange(range);msg('Link selezionato: copialo e mandalo agli amici.')}}}
function field(id,label,value='',type='text',extra=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function cameraControls(live=false,busy=false){
 const captureButton=document.querySelector('[data-moment-action="capture"]'),cameraButton=document.querySelector('[data-moment-action="camera"]');
 if(captureButton){captureButton.hidden=!live;captureButton.disabled=busy}
 if(cameraButton){cameraButton.hidden=live;cameraButton.disabled=busy;cameraButton.textContent=draft?'Rifai la foto':'Apri fotocamera'}
 for(const button of document.querySelectorAll('[data-moment-action="camera-front"],[data-moment-action="camera-back"]')){button.disabled=busy;button.setAttribute('aria-pressed',String(button.dataset.momentAction===(cameraMode==='user'?'camera-front':'camera-back')))}
 const choices=document.querySelector('#moment-camera-device');if(choices)choices.disabled=busy;
 const status=document.querySelector('#moment-camera-status');if(status)status.textContent=busy?'Apertura fotocamera…':live?(cameraMode==='user'?'Fotocamera frontale':'Fotocamera posteriore'):'Scegli frontale o posteriore, poi apri la fotocamera.';
}
function stopCamera(){cameraGeneration++;cameraBusy=false;stream?.getTracks().forEach(t=>t.stop());stream=null;const video=document.querySelector('#moment-video');if(video){video.srcObject=null;video.hidden=true}cameraControls();const placeholder=document.querySelector('#moment-camera-placeholder');if(placeholder)placeholder.hidden=!!draft}
function paintCameraDevices(){
 const picker=document.querySelector('#moment-camera-device'),wrap=document.querySelector('#moment-camera-device-field');if(!picker||!wrap)return;
 const selected=stream?.getVideoTracks()[0]?.getSettings?.().deviceId;
 picker.innerHTML='<option value="">Obiettivo automatico</option>'+cameraDevices.map((device,i)=>'<option value="'+esc(device.deviceId)+'" '+(device.deviceId===selected?'selected':'')+'>'+esc(device.label||'Fotocamera '+(i+1))+'</option>').join('');
 wrap.hidden=cameraDevices.length<3;picker.disabled=cameraBusy;
}
function compose(){if(!online()){msg('Per pubblicare un momento serve internet.');return}stopCamera();if(draft?.url)URL.revokeObjectURL(draft.url);draft=null;coords=null;capturedAt=null;cameraMode='user';cameraDevices=[];dialog('Questo momento è nostro.',`<div class="moment-camera"><video id="moment-video" autoplay playsinline muted hidden></video><img id="moment-preview" alt="La tua foto prima della pubblicazione" hidden><div id="moment-camera-placeholder">${icon('camera')}<p>Un selfie o il panorama?</p></div></div><div class="moment-camera-choice" role="group" aria-label="Scegli fotocamera"><button class="secondary" data-moment-action="camera-front" aria-pressed="true">🤳 Frontale</button><button class="secondary" data-moment-action="camera-back" aria-pressed="false">📷 Posteriore</button></div><div id="moment-camera-device-field" class="field" hidden><label for="moment-camera-device">Fotocamera / obiettivo</label><select id="moment-camera-device"></select></div><p id="moment-camera-status" class="moment-fine" role="status">Scegli frontale o posteriore, poi apri la fotocamera.</p><div class="moment-camera-actions"><button class="primary" data-moment-action="camera">Apri fotocamera</button><button class="primary" data-moment-action="capture" hidden>Scatta</button><button class="secondary" data-moment-action="pick">Scegli una foto</button><input id="moment-file" type="file" accept="image/*" hidden></div><p class="moment-fine camera-lens-help">Non trovi il grandangolo 0,5×? Scatta con l’app Fotocamera del telefono e usa “Scegli una foto”.</p><form id="moment-post-form"><div class="field"><label for="moment-caption">Una frase per ricordarlo <span>(facoltativa)</span></label><textarea id="moment-caption" maxlength="600" rows="3" placeholder="Persi a Tokyo. Felici, però."></textarea></div>${field('moment-place','Dove siete? (facoltativo)','','text','maxlength="100" placeholder="Es. Shibuya, Tokyo"')}<div class="moment-gps-row"><button type="button" class="secondary" data-moment-action="gps">Aggiungi posizione GPS</button><button type="button" class="text-button" data-moment-action="remove-gps" hidden>Rimuovi</button></div><p id="moment-gps-status" class="moment-fine">La posizione viene condivisa soltanto se la aggiungi.</p><p id="moment-photo-status" class="moment-fine"></p><button class="primary moment-publish" type="submit" disabled>Pubblica nel gruppo ${icon('arrow')}</button></form>`)}
function cameraDeviceMode(deviceId,fallback=cameraMode){const label=cameraDevices.find(device=>device.deviceId===deviceId)?.label||'';if(/back|rear|posteriore|environment|arrière|rück/i.test(label))return 'environment';if(/front|user|anteriore|facetime|avant/i.test(label))return 'user';return fallback}
async function startCamera(mode=cameraMode,deviceId=''){
 if(cameraBusy)return;
 if(deviceId)mode=cameraDeviceMode(deviceId,mode);
 stopCamera();cameraMode=mode;cameraBusy=true;const generation=cameraGeneration;cameraControls(false,true);
 const current=()=>generation===cameraGeneration&&!!document.querySelector('#moment-video')&&!!document.querySelector('#moment-dialog')?.open;
 try{
  if(!navigator.mediaDevices?.getUserMedia)throw Error('Fotocamera non disponibile: usa Scegli una foto.');
  const settings={width:{ideal:1600},height:{ideal:1200}};
  let acquired;
  try{acquired=await navigator.mediaDevices.getUserMedia({video:{...settings,...(deviceId?{deviceId:{exact:deviceId}}:{facingMode:{exact:mode}})},audio:false})}
  catch(error){if(deviceId||!['OverconstrainedError','NotFoundError'].includes(error.name)||!current())throw error;acquired=await navigator.mediaDevices.getUserMedia({video:{...settings,facingMode:{ideal:mode}},audio:false})}
  if(!current()){acquired.getTracks().forEach(track=>track.stop());return}
  stream=acquired;const video=document.querySelector('#moment-video'),track=stream.getVideoTracks()[0],actual=track?.getSettings?.().facingMode;
  if(actual==='user'||actual==='environment')cameraMode=actual;
  video.dataset.facing=cameraMode;video.srcObject=stream;video.hidden=false;await video.play();
  if(!current())return;
  document.querySelector('#moment-preview').hidden=true;document.querySelector('#moment-camera-placeholder').hidden=true;document.querySelector('#moment-error').textContent='';
  cameraBusy=false;cameraControls(true);
  if(actual&&actual!==mode&&!deviceId)document.querySelector('#moment-camera-status').textContent='Questa è la fotocamera disponibile sul dispositivo.';
  try{cameraDevices=(await navigator.mediaDevices.enumerateDevices()).filter(device=>device.kind==='videoinput'&&device.deviceId);if(current())paintCameraDevices()}catch{}
 }catch(error){if(!current())return;stopCamera();const message=document.querySelector('#moment-error');if(message)message.textContent=error.name==='NotAllowedError'?'Accesso alla fotocamera negato. Puoi usare Scegli una foto o riattivare il permesso nelle impostazioni del browser.':error.name==='NotFoundError'||error.name==='OverconstrainedError'?'Questa fotocamera non è disponibile. Prova l’altra o usa Scegli una foto.':friendly(error)}
 finally{if(generation===cameraGeneration&&cameraBusy){cameraBusy=false;cameraControls(!!stream)}}
}
async function chooseCamera(mode){if(cameraBusy)return;cameraMode=mode;const picker=document.querySelector('#moment-camera-device');if(picker)picker.value='';if(stream)await startCamera(mode);else cameraControls()}
document.addEventListener('change',event=>{if(event.target.id==='moment-camera-device')void startCamera(cameraMode,event.target.value)});

async function compressed(image,w,h){if(!w||!h)throw Error('La foto non è leggibile.');const scale=Math.min(1,1200/Math.max(w,h)),canvas=document.createElement('canvas');canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);let blob;for(const quality of [.82,.68,.52,.38]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(blob&&blob.size<=MAX_BYTES)break}if(!blob||blob.size>MAX_BYTES)throw Error('Questa foto è troppo grande. Scegline un’altra.');return blob}
function usePhoto(blob,source){if(draft?.url)URL.revokeObjectURL(draft.url);draft={blob,url:URL.createObjectURL(blob),source};capturedAt=new Date().toISOString();stopCamera();document.querySelector('#moment-video').hidden=true;const image=document.querySelector('#moment-preview');image.src=draft.url;image.hidden=false;document.querySelector('#moment-camera-placeholder').hidden=true;document.querySelector('[data-moment-action="capture"]').hidden=true;document.querySelector('[data-moment-action="camera"]').hidden=false;document.querySelector('[data-moment-action="camera"]').textContent='Rifai la foto';document.querySelector('.moment-publish').disabled=false;document.querySelector('#moment-photo-status').textContent=`${source==='camera'?'Foto scattata ora':'Foto selezionata ora'} · ${Math.ceil(blob.size/1000)} KB. Verrà inviata solo quando premi Pubblica.`;document.querySelector('#moment-error').textContent=''}
async function capture(){try{const v=document.querySelector('#moment-video');usePhoto(await compressed(v,v.videoWidth,v.videoHeight),'camera')}catch(e){document.querySelector('#moment-error').textContent=friendly(e)}}
async function pickFile(file){if(!file)return;try{if(file.size>25000000)throw Error('Scegli una foto più piccola di 25 MB.');const url=URL.createObjectURL(file),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('Formato non leggibile. Su iPhone scegli una foto JPEG oppure usa la fotocamera.'));img.src=url});usePhoto(await compressed(img,img.naturalWidth,img.naturalHeight),'gallery')}finally{URL.revokeObjectURL(url)}}catch(e){document.querySelector('#moment-error').textContent=friendly(e)}}
function gps(){const b=document.querySelector('[data-moment-action="gps"]'),target=document.querySelector('#moment-gps-status');b.disabled=true;document.querySelector('#moment-gps-status').textContent='Cerchiamo la posizione…';if(!navigator.geolocation){b.disabled=false;msg('GPS non disponibile. Puoi scrivere il nome del luogo.');return}navigator.geolocation.getCurrentPosition(p=>{b.disabled=false;if(document.querySelector('#moment-gps-status')!==target||!document.querySelector('#moment-dialog')?.open)return;coords={latitude:Number(p.coords.latitude.toFixed(4)),longitude:Number(p.coords.longitude.toFixed(4))};document.querySelector('#moment-gps-status').textContent='Posizione aggiunta: '+coords.latitude+', '+coords.longitude+' · precisione circa '+Math.round(p.coords.accuracy)+' m. Sarà visibile al gruppo.';document.querySelector('[data-moment-action="remove-gps"]').hidden=false},e=>{b.disabled=false;if(document.querySelector('#moment-gps-status')!==target)return;document.querySelector('#moment-gps-status').textContent=e.code===1?'Permesso GPS negato. Il post potrà essere pubblicato senza posizione.':'Posizione non disponibile. Riprova o scrivi il nome del luogo.'},{enableHighAccuracy:false,timeout:12000,maximumAge:0})}
async function blobBase64(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)}
async function publish(){if(!draft)return;const el=document.querySelector('#moment-dialog'),b=el.querySelector('.moment-publish');el.dataset.busy='true';el.querySelectorAll('button').forEach(button=>button.disabled=true);b.textContent='Pubblicazione…';try{draft.id=draft.id||crypto.randomUUID();const photo=await blobBase64(draft.blob);await rpc('publish',{id:draft.id,photo,caption:document.querySelector('#moment-caption').value.trim(),place:document.querySelector('#moment-place').value.trim(),captured_at:capturedAt,source:draft.source,latitude:coords?.latitude??null,longitude:coords?.longitude??null});el.close();if(draft?.url)URL.revokeObjectURL(draft.url);draft=null;await loadFeed(false,true);msg('Momento pubblicato. Gli amici lo vedranno nel diario.')}catch(e){document.querySelector('#moment-error').textContent=friendly(e)}finally{el.dataset.busy='false';el.querySelectorAll('button').forEach(button=>button.disabled=false);b.disabled=!draft;b.innerHTML='Pubblica nel gruppo '+icon('arrow')}}
function confirmDelete(p){dialog('Eliminare questo momento?',`<p>Il post di ${esc(p.author_name)} verrà rimosso dal diario e la foto spostata nel cestino del Drive dell’organizzatore.</p><div class="dialog-actions"><button class="secondary" data-moment-action="close">Annulla</button><button class="primary" data-moment-action="confirm-delete" data-post="${esc(p.id)}">Elimina momento</button></div>`)}
async function deletePost(p){const el=document.querySelector('#moment-dialog');el.dataset.busy='true';el.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await rpc('delete',{id:p.id});posts=posts.filter(a=>a.id!==p.id);trimImages();revision=null;el.close();paintFeed();msg(result.cleaned?'Momento eliminato dal diario. La foto è nel cestino di Drive.':'Post rimosso dal diario. L’organizzatore deve spostare la foto nel cestino direttamente da Drive.')}catch(e){document.querySelector('#moment-error').textContent=friendly(e)}finally{el.dataset.busy='false';el.querySelectorAll('button').forEach(b=>b.disabled=false)}}
async function members(){const list=await rpc('members');dialog('I compagni di viaggio',`<p>${list.length} partecipanti nel diario. Rimuovere una persona revoca il suo accesso e cambia anche l’invito, così il vecchio link non permette di rientrare.</p><div class="moment-member-list">${list.map(m=>`<div class="moment-member"><strong>${esc(m.name)}</strong>${m.id===uid()?'<span>Tu · organizzatore</span>':`<button class="text-button danger-text" data-moment-action="remove-member" data-member="${esc(m.id)}" data-name="${esc(m.name)}">Rimuovi</button>`}</div>`).join('')}</div>`)}
document.addEventListener('submit',e=>{const id=e.target.id;if(!['moment-setup-form','moment-join-form','moment-post-form'].includes(id))return;e.preventDefault();if(document.querySelector('#moment-dialog').dataset.busy==='true')return;void(id==='moment-post-form'?publish():submitAccess(id==='moment-setup-form'?'setup':'join'))});
document.addEventListener('change',e=>{if(e.target.id==='moment-file')void pickFile(e.target.files[0])});
document.addEventListener('click',async e=>{const el=e.target.closest('[data-moment-action]');if(!el)return;const action=el.dataset.momentAction,p=posts.find(p=>p.id===el.dataset.post),d=document.querySelector('#moment-dialog');if(d?.dataset.busy==='true')return;try{switch(action){case'setup':setup();break;case'join':join();break;case'close':d.close();break;case'compose':compose();break;case'camera':await startCamera();break;case'camera-front':await chooseCamera('user');break;case'camera-back':await chooseCamera('environment');break;case'capture':await capture();break;case'pick':document.querySelector('#moment-file').click();break;case'gps':gps();break;case'remove-gps':coords=null;document.querySelector('#moment-gps-status').textContent='Posizione rimossa. Non verrà condivisa.';el.hidden=true;break;case'refresh':await loadFeed(false,true);break;case'older':await loadFeed(true);break;case'filter-all':case'filter-mine':if(loading)break;filter=action==='filter-all'?'all':'mine';posts=[];revision=null;lastFetch=0;loadGeneration++;await loadFeed(false,true);break;case'photo':if(p)await photo(p);break;case'group':group();break;case'invite':await copyInvite();break;case'rename':pendingInvite=null;join();break;case'rotate':dialog('Sostituire il link d’invito?',`<p>Il vecchio link non permetterà più di entrare. Gli amici già nel gruppo rimarranno collegati.</p><button class="primary" data-moment-action="confirm-rotate">Genera nuovo link</button>`);break;case'confirm-rotate':{const data=await rpc('rotate');cfg.invite=data.invite;save();group();msg('Nuovo invito pronto. Copialo e mandalo agli amici.');break}case'download':if(p){const url=await photo(p);if(url){const a=document.createElement('a');a.href=url;a.download='Giappone-'+japanDate(p.created_at)+'-'+p.id.slice(0,8)+'.jpg';a.click()}}break;case'delete':if(p)confirmDelete(p);break;case'confirm-delete':if(p)await deletePost(p);break;case'members':await members();break;case'remove-member':dialog('Rimuovere '+esc(el.dataset.name)+'?',`<p>La persona perderà l’accesso al diario. Anche il link d’invito cambierà; gli altri partecipanti resteranno collegati.</p><button class="primary" data-moment-action="confirm-remove-member" data-member="${esc(el.dataset.member)}">Rimuovi e cambia invito</button>`);break;case'confirm-remove-member':{const result=await rpc('removeMember',{id:el.dataset.member});cfg.invite=result.invite;save();group();msg('Accesso revocato. Se serve, copia il nuovo invito per il gruppo.');break}}}catch(error){const current=document.querySelector('#moment-dialog');if(current?.open&&current.querySelector('#moment-error'))current.querySelector('#moment-error').textContent=friendly(error);else msg(friendly(error))}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();else if(active&&ready()&&!browsingOlder&&Date.now()-lastFetch>30000)void loadFeed()});window.addEventListener('pagehide',stopCamera);window.addEventListener('online',()=>{if(active)void loadFeed(false,true)});window.addEventListener('offline',()=>{if(active)msg('Sei offline. Le foto richiedono internet; il programma resta disponibile.')});setInterval(()=>{if(active&&!document.hidden&&ready()&&!browsingOlder&&online()&&!document.querySelector('#moment-dialog')?.open)void loadFeed()},30000);
window.addEventListener('hashchange',()=>{try{const encoded=new URLSearchParams(location.hash.slice(1)).get('momenti');if(!encoded)return;const invitation=JSON.parse(atob(encoded.replace(/-/g,'+').replace(/_/g,'/')));window.MOMENT_DRIVE_TRANSPORT.validate(invitation.url);if(invitation.provider!=='google-drive'||!/^[a-f0-9]{64}$/.test(invitation.invite))throw Error('Invito non valido');incomingInvite=invitation;if(cfg?.url===invitation.url&&cfg?.token&&!accessLost){cfg.invite=invitation.invite;save()}else{pendingInvite=invitation;accessLost=false;}document.querySelector('.main-tabs [data-view="moments"]')?.click();paintMain();}catch{msg('Il nuovo invito non è valido. Chiedi un altro link all’organizzatore.')}});
window.JAPAN_MOMENTS={render,onView,icon};
})();
