/* Shared itinerary. GitHub is the source; credentials exist only in editor memory. */
(()=>{'use strict';
const API='https://api.github.com/repos/RobertoCipriani/Giappone-2026/contents/Giappone2026/programma.json',FILE='programma.json',K='roberto-japan-2026-v1',CACHE=K+'-published',DRAFT=K+'-editor-draft',BACKUP=K+'-personal-backup';
const clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function envelope(raw,validate){if(!raw||raw.format!=='giappone-programma-condiviso-v1'||typeof raw.published!=='boolean'||typeof raw.revision!=='string'||raw.revision.length>100||!raw.revision||typeof raw.updatedAt!=='string'||!Number.isFinite(Date.parse(raw.updatedAt))||!['Roberto','Leonardo','Setup'].includes(raw.editor))throw Error('Il programma condiviso non è valido.');return {format:raw.format,published:raw.published,revision:raw.revision,updatedAt:raw.updatedAt,editor:raw.editor,program:validate(raw.program)}}
function cleanProgram(raw,validate){const p=validate(raw);for(const d of p.days)for(const e of d.events)e.done=false;return p}
function base64(text){const bytes=new TextEncoder().encode(text);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)}
function unbase64(text){return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(String(text).replace(/\s/g,'')),c=>c.charCodeAt(0)))}
function protocol(fetcher,validate){
 async function request(token,method='GET',body){if(!/^github_pat_[A-Za-z0-9_]{20,}$/.test(token))throw Error('Serve una chiave fine-grained GitHub limitata a questo progetto.');let response;try{response=await fetcher(API+(method==='GET'?'?ref=main&t='+Date.now():''),{method,cache:'no-store',credentials:'omit',redirect:'error',referrerPolicy:'no-referrer',headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})}catch{throw Error('Connessione interrotta. La bozza resta salvata; verifica la pubblicazione prima di riprovare.')}if(!response.ok){const message=response.status===409?'CONFLICT':response.status===401?'Chiave scaduta o non valida.':response.status===403?'La chiave non ha accesso Contents: Read and write a questo progetto, oppure GitHub ha raggiunto un limite temporaneo.':response.status===404?'La chiave non ha accesso al progetto o il file condiviso non è disponibile.':response.status===422?'GitHub non ha accettato il salvataggio. Attendi e riprova.':'GitHub non ha risposto correttamente.';throw Error(message)}return response.json()}
 async function read(token){const r=await request(token);if(typeof r.sha!=='string'||r.encoding!=='base64'||typeof r.content!=='string'||r.size>850000)throw Error('La versione GitHub non è leggibile.');return {sha:r.sha,envelope:envelope(JSON.parse(unbase64(r.content)),validate)}}
 async function publish(token,baseRevision,draft,editor,revision){if(!['Roberto','Leonardo'].includes(editor))throw Error('Scegli Roberto o Leonardo.');const current=await read(token);if(current.envelope.revision===revision)return current;if(current.envelope.revision!==baseRevision)throw Error('CONFLICT');const next={format:'giappone-programma-condiviso-v1',published:true,revision,updatedAt:new Date().toISOString(),editor,program:cleanProgram(draft,validate)};next.program.updatedAt=next.updatedAt;const text=JSON.stringify(next,null,2)+'\n';if(new TextEncoder().encode(text).length>850000)throw Error('Il programma è troppo grande: esporta una copia e riduci le informazioni.');try{const result=await request(token,'PUT',{message:'Programma del viaggio aggiornato da '+editor,content:base64(text),sha:current.sha,branch:'main'});if(!result.content?.sha)throw Error('Pubblicazione da verificare.');return {sha:result.content.sha,envelope:next}}catch(error){if(error.message==='CONFLICT')throw error;try{const check=await read(token);if(check.envelope.revision===revision)return check}catch{}throw error}}
 return {read,publish}
}
let hooks,installed=false,admin=false,ready=false,active=false,busy=false,reading=false,token='',name='Roberto',remote=null,baseRevision=null,dirty=false,pending=null,status='Controllo il programma condiviso…',boot=true,conflicted=false,changeVersion=0;
function saved(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
function download(value,label){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=label+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function backup(){if(saved(BACKUP))return;const old=saved(K);if(old)save(BACKUP,old)}
function saveDraft(){if(!admin||!ready)return;dirty=true;changeVersion++;if(!busy)pending=null;const p=hooks.get();if(!save(DRAFT,{baseRevision,program:p,pending,updatedAt:new Date().toISOString()}))status='Spazio del browser esaurito: esporta la bozza prima di chiudere.';else status='Bozza salvata su questo dispositivo · da pubblicare per il gruppo.';paint()}
function setProgram(program){hooks.set(clone(program));hooks.render()}
function startEditor(e){const draft=saved(DRAFT);if(draft){try{hooks.set(hooks.validate(draft.program));baseRevision=draft.baseRevision;pending=draft.pending||null;dirty=true;conflicted=baseRevision!==e.revision;status=conflicted?'Esiste una bozza precedente: confrontala con la versione pubblicata prima di pubblicare.':'La tua bozza è stata recuperata.'}catch{baseRevision=e.revision;hooks.set(clone(e.published?e.program:hooks.get()));status='La vecchia bozza non è leggibile. Esporta la copia personale se contiene modifiche.'}}else{baseRevision=e.revision;if(e.published)hooks.set(clone(e.program));status=e.published?'Stai modificando l’ultima versione pubblicata.':'Prima pubblicazione: la copia su questo dispositivo è pronta da modificare.'}hooks.setEditing(true);ready=true;boot=false;hooks.render();paint()}
function accept(e){remote=e;active=e.published;if(admin){if(boot)startEditor(e);else if(e.revision!==baseRevision){conflicted=true;status='È stata pubblicata un’altra versione. La tua bozza rimane intatta.'}paint();return}ready=true;boot=false;if(!e.published){status='Programma iniziale · in attesa della prima pubblicazione degli organizzatori.';paint();return}backup();hooks.rememberDone();setProgram(e.program);status='Programma condiviso aggiornato';paint()}
async function refresh(manual=false){if(!installed||reading||busy||!navigator.onLine||document.hidden)return;if(!admin&&document.querySelector('dialog[open]'))return;reading=true;try{const url=new URL(FILE,location.href);url.searchParams.set('t',Date.now());const r=await fetch(url.href,{cache:'no-store',credentials:'omit',redirect:'error'});if(!r.ok)throw Error('OFFLINE');const text=await r.text();if(text.length>850000)throw Error('SIZE');const e=envelope(JSON.parse(text),hooks.validate);if(remote&&Date.parse(e.updatedAt)<Date.parse(remote.updatedAt))return;const changed=!remote||e.revision!==remote.revision;save(CACHE,e);if(changed||boot)accept(e);else if(!admin){status='Programma condiviso aggiornato';paint()}if(manual)hooks.toast(admin?'Versione pubblicata controllata. La bozza è conservata.':'Programma aggiornato.')}catch{if(boot){const cached=saved(CACHE);if(cached){try{accept(envelope(cached,hooks.validate))}catch{}}}if(boot&&admin){ready=false;status='Collegati a internet per caricare la versione condivisa. Le modifiche precedenti sono conservate.'}else status=navigator.onLine?'Aggiornamento non disponibile: resta l’ultima copia salvata.':'Copia offline';paint();if(manual)hooks.toast(status)}finally{reading=false}}
function controls(){if(document.querySelector('#program-admin'))return;const b=document.createElement('section');b.id='program-admin';b.className='program-admin';b.innerHTML='<div><span class="eyebrow">ROBERTO & LEONARDO</span><h2>Gestione del viaggio</h2><p id="program-admin-status" role="status"></p></div><div class="program-admin-actions"><button class="primary" data-program="publish">Pubblica per tutti</button><button class="secondary" data-program="connect">Collega accesso</button><button class="secondary" data-program="current">Carica versione pubblicata</button><button class="secondary" data-program="recover">Recupera copia personale</button><button class="secondary" data-program="export">Esporta bozza</button><a class="program-help" href="guida-gestione.html" target="_blank" rel="noopener">Guida ai due accessi</a><a class="program-help" href="./" target="_blank" rel="noopener">Apri il sito del gruppo</a></div><p class="program-admin-note">Le modifiche sono una bozza fino a “Pubblica per tutti”. Descrizioni, note, orari, link e prenotazioni saranno pubblici come il sito del viaggio.</p>';document.querySelector('main').before(b);
const d=document.createElement('dialog');d.id='program-access';d.className='sync-setup';d.innerHTML='<form id="program-access-form"><div class="dialog-heading"><h2>Il tuo accesso di gestione</h2><button type="button" class="icon-button" data-program="close" aria-label="Chiudi">×</button></div><p>La chiave viene inviata soltanto a GitHub per pubblicare il programma. Rimane in memoria in questa scheda e va reinserita dopo una ricarica.</p><div class="field"><label for="program-name">Chi sta aggiornando?</label><select id="program-name"><option>Roberto</option><option>Leonardo</option></select></div><div class="field"><label for="program-token">Chiave privata di questo progetto</label><input id="program-token" type="password" autocomplete="off" spellcheck="false" required placeholder="github_pat_…"></div><p id="program-access-error" class="form-error" role="alert"></p><p><a href="guida-gestione.html" target="_blank" rel="noopener">Come attivare i due accessi</a></p><div class="dialog-actions"><button type="button" class="secondary" data-program="close">Annulla</button><button class="primary" type="submit">Collega accesso</button></div></form>';document.body.append(d);
d.addEventListener('close',()=>{document.querySelector('#program-token').value='';document.querySelector('#program-access-error').textContent=''});
document.querySelector('#program-access-form').onsubmit=async event=>{event.preventDefault();const input=document.querySelector('#program-token'),proposed=input.value.trim(),button=event.submitter;button.disabled=true;document.querySelector('#program-access-error').textContent='';try{const current=await protocol(fetch,hooks.validate).read(proposed);token=proposed;name=document.querySelector('#program-name').value;remote=current.envelope;conflicted=ready&&baseRevision!==remote.revision;if(!ready)startEditor(remote);status=conflicted?'Accesso collegato. È stata pubblicata un’altra versione: confronta la tua bozza.':'Accesso collegato per '+name+'. Puoi pubblicare la bozza.';d.close();paint()}catch(error){document.querySelector('#program-access-error').textContent=error.message}finally{button.disabled=false}};
}
function paint(){if(!installed)return;const badge=document.querySelector('#save-state');if(badge){badge.textContent=admin?(busy?'Pubblicazione…':dirty?'Bozza da pubblicare':'Gestione programma'):!navigator.onLine?'Copia offline':active?'Programma condiviso':'Programma pronto';badge.title=status}const edit=document.querySelector('#edit-toggle');if(edit){edit.hidden=!admin||!ready||busy||['moments','more'].includes(hooks.view());edit.textContent=hooks.isEditing()?'Fine modifica':'Modifica';edit.setAttribute('aria-pressed',hooks.isEditing())}for(const el of document.querySelectorAll('[data-action="configure-sync"],[data-action="sync-now"]'))el.hidden=true;for(const el of document.querySelectorAll('[data-action="import"],[data-action="undo"],[data-action="reset"]'))el.hidden=!admin;const desc=document.querySelector('.sync-description');if(desc)desc.textContent=status;if(!admin)return;controls();document.querySelector('#program-admin-status').textContent=status;const publish=document.querySelector('[data-program="publish"]');publish.disabled=busy||!ready||conflicted;document.querySelector('[data-program="connect"]').textContent=token?'Cambia accesso':'Collega accesso';for(const button of document.querySelectorAll('#program-admin button:not([data-program="publish"])'))button.disabled=busy;const banner=document.querySelector('.editing-banner');if(banner)banner.textContent='Bozza organizzatori · premi “Pubblica per tutti” per aggiornare il gruppo.'}
async function publish(){if(!ready||busy)return;if(!token){document.querySelector('#program-access').showModal();return}if(document.querySelector('dialog[open]')){hooks.toast('Salva prima l’attività aperta.');return}const captured=hooks.get();const version=changeVersion;pending=pending||crypto.randomUUID();save(DRAFT,{baseRevision,program:captured,pending,updatedAt:new Date().toISOString()});busy=true;hooks.setEditing(false);status='Pubblicazione su GitHub…';paint();hooks.render();try{const result=await protocol(fetch,hooks.validate).publish(token,baseRevision,captured,name,pending);remote=result.envelope;baseRevision=remote.revision;active=true;conflicted=false;save(CACHE,remote);pending=null;if(version===changeVersion){dirty=false;try{localStorage.removeItem(DRAFT)}catch{}}else save(DRAFT,{baseRevision,program:hooks.get(),pending:null,updatedAt:new Date().toISOString()});status='Salvato nel progetto GitHub. Il gruppo lo riceverà automaticamente dopo la pubblicazione del sito.';hooks.toast('Programma pubblicato per tutti. GitHub sta aggiornando il sito.')}catch(error){conflicted=error.message==='CONFLICT';status=conflicted?'L’altro organizzatore ha pubblicato prima di te. Esporta la bozza e carica la versione pubblicata per confrontarle.':error.message;hooks.toast(status)}finally{busy=false;hooks.setEditing(true);hooks.render();paint()}}
function loadLatest(){if(!token){document.querySelector('#program-access').showModal();return}hooks.confirm('Caricare la versione pubblicata?','La bozza attuale verrà prima esportata. Potrai riprendere le informazioni dal file scaricato.',async()=>{try{const current=await protocol(fetch,hooks.validate).read(token);download(hooks.get(),'Giappone_bozza_prima_del_confronto');remote=current.envelope;baseRevision=remote.revision;conflicted=false;pending=null;dirty=false;try{localStorage.removeItem(DRAFT)}catch{}setProgram(remote.program);status='Ultima versione caricata. Integra le modifiche della tua bozza, poi pubblica.';paint()}catch(error){hooks.toast(error.message)}})}
function recover(){const old=saved(BACKUP)||saved(K);if(!old){hooks.toast('Su questo browser non è presente una copia personale. Apri Gestione dal dispositivo usato per le modifiche, oppure importa il file esportato.');return}hooks.confirm('Recuperare le modifiche personali?','La bozza attuale verrà esportata. La copia recuperata sostituirà la bozza da rivedere prima di pubblicare.',()=>{try{const p=hooks.validate(old);download(hooks.get(),'Giappone_bozza_prima_del_recupero');setProgram(p);saveDraft();hooks.toast('Copia personale recuperata nella bozza. Controllala prima di pubblicare.')}catch(error){hooks.toast(error.message)}})}
function install(h){hooks=h;installed=true;admin=new URL(location.href).searchParams.get('gestione')==='1';if(admin){backup();hooks.setEditing(false);controls()}else{hooks.setEditing(false);const c=saved(CACHE);if(c)try{accept(envelope(c,hooks.validate))}catch{}}document.addEventListener('click',event=>{const el=event.target.closest('[data-program]');if(!el||!admin)return;switch(el.dataset.program){case'publish':publish();break;case'connect':document.querySelector('#program-access').showModal();break;case'close':document.querySelector('#program-access').close();break;case'current':loadLatest();break;case'recover':recover();break;case'export':download(hooks.get(),'Giappone_bozza');break}});document.addEventListener('click',event=>{if(busy&&event.target.closest('button')){event.preventDefault();event.stopImmediatePropagation()}},true);window.addEventListener('beforeunload',event=>{if(admin&&(dirty||busy)){event.preventDefault();event.returnValue=''}});window.addEventListener('pagehide',()=>{token=''});refresh();paint()}
window.JAPAN_PROGRAM_SHARED={install,refresh,paint,changed:saveDraft,ownsProgram:()=>installed,get installed(){return installed},get admin(){return admin},get busy(){return busy},get active(){return active},test:{envelope,cleanProgram,base64,unbase64,protocol}};
})();